name_length: 50
email_length: 250
password_min_length: 6
gravatar_size: 80
gravatar_small: 50
checked: "1"
default_email: "noreply@example.com"
address: "smtp.gmail.com"
port: 587
authentication: "plain"
enable: true
domain: "example.com"
host: "localhost:3000"
protocol: "http"
password_expired: 2
content_max: 140
max_size: 5
image_extensions: "image/jpeg,image/gif,image/png"
